import { init } from 'grovedom';
import { init as initBrowser } from '../src/browser.js';
import { init as initNative } from '../src/native.js';
init({ wasm: new Uint8Array(), heap: 'pool', poolSize: 8 });
const browserReady: Promise<void> = initBrowser({ wasm: new Uint8Array() });
initNative({ addon: new URL('file:///example.node') });
import { load, merge, contains, type FilterFunction, type NodeHandle, type SelectorType } from 'grovedom';
const $ = load('<p>Hello</p>', { scriptingEnabled: true });
const selector: SelectorType = 'p';
const filter: FilterFunction<NodeHandle> = function (i, node) { return this === node && i === 0; };
const text: string = $(selector).filter(filter).text();
$(selector).attr('title', function (i, old) { return `${this.name} ${i} ${old}`; }).text(text);
$(selector).each(function (i, node) { $(node).attr('data-i', i); });
const first = $(selector)[0];
if (first) $(first).html('<b>x</b>');
const children: NodeHandle[] | undefined = first?.children;
const xml = load('<x/>', { xmlMode: true });
const serializedXML: string = xml.xml();
const renderedXML: string = xml.html({ xml: { selfClosingTags: false, encodeEntities: true } });
const renderedNodes: string = xml.html(xml('x').get(), { xmlMode: true });
// @ts-expect-error Parser callbacks are not per-call serializer options.
xml.html({ onopentag() {} });
xml.dispose();
load('<Root/>', { xml: { lowerCaseTags: false, xmlMode: true, recognizeSelfClosing: true } }).dispose();
// @ts-expect-error XML callbacks are not supported.
load('<x/>', { xml: { onopentag() {} } });
$(selector).wrap('<div/>');
$(selector).prop('tagName', 'div');
const names: (string | undefined)[] = $('p').map((i, node) => node.name).get();
$('p').map((i, node) => node).attr('title', 'mapped');
const extracted: { labels: string[] } = $.extract({ labels: ['p'] });
const scores: { scores: number[] } = $.extract({ scores: [{ selector: 'p', value: node => $(node).text().length }] });
$('input').val('x').data('saved', true).css('color', 'red');
// @ts-expect-error Handles are not mutable domhandler trees.
if (first) first.parent = null;
$.dispose();
const buffered = load(Buffer.from('<template><p>Hello</p></template>'));
const marker: string = buffered('p').cheerio;
const html: string | null | undefined = buffered('p').prop('innerHTML');
const combined: ArrayLike<number> | undefined = merge([1], [2]);
const fragment = buffered('template').contents()[0]!;
const included: boolean = contains(buffered('template')[0]!, fragment);
const removed: NodeHandle[] = buffered('p').splice(0, 1);
buffered.dispose();
