// Generate the Unicode data used by the rare selector comparison path. Runtime
// consumers need neither ICU nor Node. Regenerate with Unicode 17.0.
import { writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
assert.equal(process.versions.unicode, '17.0', 'Use the reviewed Unicode version');
const lower = [], canonical = [], properties = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
  const s = String.fromCodePoint(cp), lo = [...s.toLowerCase()];
  if (lo.length === 1 && lo[0].codePointAt(0) !== cp) lower.push([cp, lo[0].codePointAt(0) - cp]);
  else if (lo.length !== 1) assert.equal(cp, 0x130, 'Review new expanding lowercase mappings');
  if (cp <= 0xffff) {
    const up = s.toUpperCase();
    if (up.length === 1 && !(cp >= 128 && up.charCodeAt(0) < 128) && up.charCodeAt(0) !== cp)
      canonical.push([cp, up.charCodeAt(0) - cp]);
  }
  const flags = (/\p{Cased}/u.test(s) ? 1 : 0) | (/\p{Case_Ignorable}/u.test(s) ? 2 : 0);
  if (flags) properties.push([cp, flags]);
}
function ranges(items) {
  const out = [];
  for (const [cp, value] of items) {
    const prev = out.at(-1);
    if (prev && prev[1] + 1 === cp && prev[2] === value) prev[1] = cp;
    else out.push([cp, cp, value]);
  }
  return out;
}
const tables = { lower, canonical, properties };
writeFileSync(new URL('../native/unicode-data.h', import.meta.url),
  '// Generated by scripts/generate-unicode.mjs; Unicode 17.0. Do not edit.\n' +
  '// Derived Unicode data: see licenses/unicode/LICENSE.\n' +
  '// Simple lowercase, ECMAScript non-Unicode regexp canonicalization, and\n' +
  '// Cased/Case_Ignorable ranges for the Final_Sigma lowercase rule.\n' +
  Object.entries(tables).map(([name, items]) => `static const gd_unicode_range gd_${name}[] = {\n` +
    ranges(items).map(([a, b, v]) => `    {0x${a.toString(16)}, 0x${b.toString(16)}, ${v}},`).join('\n') + '\n};\n').join(''));
